// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static AspNetGroupBasedPermissions.Controllers.AccountController Account = new AspNetGroupBasedPermissions.Controllers.T4MVC_AccountController();
    public static AspNetGroupBasedPermissions.Controllers.FileController File = new AspNetGroupBasedPermissions.Controllers.T4MVC_FileController();
    public static AspNetGroupBasedPermissions.Controllers.GroupsController Groups = new AspNetGroupBasedPermissions.Controllers.T4MVC_GroupsController();
    public static AspNetGroupBasedPermissions.Controllers.HomeController Home = new AspNetGroupBasedPermissions.Controllers.T4MVC_HomeController();
    public static AspNetGroupBasedPermissions.Controllers.RolesController Roles = new AspNetGroupBasedPermissions.Controllers.T4MVC_RolesController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class elfinder {
            private const string URLPATH = "~/Content/elfinder";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                private const string URLPATH = "~/Content/elfinder/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string elfinder_full_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.full.min.css") ? Url("elfinder.full.min.css") : Url("elfinder.full.css");
                     
                public static readonly string elfinder_min_css = Url("elfinder.min.css");
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                     
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class img {
                private const string URLPATH = "~/Content/elfinder/img";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string arrows_active_png = Url("arrows-active.png");
                public static readonly string arrows_normal_png = Url("arrows-normal.png");
                public static readonly string crop_gif = Url("crop.gif");
                public static readonly string dialogs_png = Url("dialogs.png");
                public static readonly string icons_big_png = Url("icons-big.png");
                public static readonly string icons_small_png = Url("icons-small.png");
                public static readonly string logo_png = Url("logo.png");
                public static readonly string progress_gif = Url("progress.gif");
                public static readonly string quicklook_bg_png = Url("quicklook-bg.png");
                public static readonly string quicklook_icons_png = Url("quicklook-icons.png");
                public static readonly string resize_png = Url("resize.png");
                public static readonly string spinner_mini_gif = Url("spinner-mini.gif");
                public static readonly string toolbar_png = Url("toolbar.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class js {
                private const string URLPATH = "~/Content/elfinder/js";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string elfinder_full_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.full.min.js") ? Url("elfinder.full.min.js") : Url("elfinder.full.js");
                public static readonly string elfinder_min_js = Url("elfinder.min.js");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class i18n {
                    private const string URLPATH = "~/Content/elfinder/js/i18n";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string elfinder_ar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.ar.min.js") ? Url("elfinder.ar.min.js") : Url("elfinder.ar.js");
                    public static readonly string elfinder_bg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.bg.min.js") ? Url("elfinder.bg.min.js") : Url("elfinder.bg.js");
                    public static readonly string elfinder_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.ca.min.js") ? Url("elfinder.ca.min.js") : Url("elfinder.ca.js");
                    public static readonly string elfinder_cs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.cs.min.js") ? Url("elfinder.cs.min.js") : Url("elfinder.cs.js");
                    public static readonly string elfinder_de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.de.min.js") ? Url("elfinder.de.min.js") : Url("elfinder.de.js");
                    public static readonly string elfinder_el_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.el.min.js") ? Url("elfinder.el.min.js") : Url("elfinder.el.js");
                    public static readonly string elfinder_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.es.min.js") ? Url("elfinder.es.min.js") : Url("elfinder.es.js");
                    public static readonly string elfinder_fa_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.fa.min.js") ? Url("elfinder.fa.min.js") : Url("elfinder.fa.js");
                    public static readonly string elfinder_fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.fr.min.js") ? Url("elfinder.fr.min.js") : Url("elfinder.fr.js");
                    public static readonly string elfinder_hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.hu.min.js") ? Url("elfinder.hu.min.js") : Url("elfinder.hu.js");
                    public static readonly string elfinder_it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.it.min.js") ? Url("elfinder.it.min.js") : Url("elfinder.it.js");
                    public static readonly string elfinder_jp_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.jp.min.js") ? Url("elfinder.jp.min.js") : Url("elfinder.jp.js");
                    public static readonly string elfinder_ko_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.ko.min.js") ? Url("elfinder.ko.min.js") : Url("elfinder.ko.js");
                    public static readonly string elfinder_LANG_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.LANG.min.js") ? Url("elfinder.LANG.min.js") : Url("elfinder.LANG.js");
                    public static readonly string elfinder_nl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.nl.min.js") ? Url("elfinder.nl.min.js") : Url("elfinder.nl.js");
                    public static readonly string elfinder_no_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.no.min.js") ? Url("elfinder.no.min.js") : Url("elfinder.no.js");
                    public static readonly string elfinder_pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.pl.min.js") ? Url("elfinder.pl.min.js") : Url("elfinder.pl.js");
                    public static readonly string elfinder_pt_BR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.pt_BR.min.js") ? Url("elfinder.pt_BR.min.js") : Url("elfinder.pt_BR.js");
                    public static readonly string elfinder_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.ru.min.js") ? Url("elfinder.ru.min.js") : Url("elfinder.ru.js");
                    public static readonly string elfinder_tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.tr.min.js") ? Url("elfinder.tr.min.js") : Url("elfinder.tr.js");
                    public static readonly string elfinder_vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.vi.min.js") ? Url("elfinder.vi.min.js") : Url("elfinder.vi.js");
                    public static readonly string elfinder_zh_CN_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/elfinder.zh_CN.min.js") ? Url("elfinder.zh_CN.min.js") : Url("elfinder.zh_CN.js");
                }
            
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class sounds {
                private const string URLPATH = "~/Content/elfinder/sounds";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string rm_wav = Url("rm.wav");
            }
        
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ui_lightness {
                private const string URLPATH = "~/Content/themes/ui-lightness";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/ui-lightness/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_diagonals_thick_18_b81900_40x40_png = Url("ui-bg_diagonals-thick_18_b81900_40x40.png");
                    public static readonly string ui_bg_diagonals_thick_20_666666_40x40_png = Url("ui-bg_diagonals-thick_20_666666_40x40.png");
                    public static readonly string ui_bg_flat_10_000000_40x100_png = Url("ui-bg_flat_10_000000_40x100.png");
                    public static readonly string ui_bg_glass_100_f6f6f6_1x400_png = Url("ui-bg_glass_100_f6f6f6_1x400.png");
                    public static readonly string ui_bg_glass_100_fdf5ce_1x400_png = Url("ui-bg_glass_100_fdf5ce_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_gloss_wave_35_f6a828_500x100_png = Url("ui-bg_gloss-wave_35_f6a828_500x100.png");
                    public static readonly string ui_bg_highlight_soft_100_eeeeee_1x100_png = Url("ui-bg_highlight-soft_100_eeeeee_1x100.png");
                    public static readonly string ui_bg_highlight_soft_75_ffe45c_1x100_png = Url("ui-bg_highlight-soft_75_ffe45c_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_228ef1_256x240_png = Url("ui-icons_228ef1_256x240.png");
                    public static readonly string ui_icons_ef8c08_256x240_png = Url("ui-icons_ef8c08_256x240.png");
                    public static readonly string ui_icons_ffd27a_256x240_png = Url("ui-icons_ffd27a_256x240.png");
                    public static readonly string ui_icons_ffffff_256x240_png = Url("ui-icons_ffffff_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                     
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                     
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                     
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                     
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                     
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                     
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                     
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                     
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                     
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                     
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                     
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                     
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                     
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                     
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                     
            }
        
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class elfinder 
            {
                public static partial class css 
                {
                    public static class Assets
                    {
                        public const string elfinder_full_css = "~/Content/elfinder/css/elfinder.full.css";
                        public const string elfinder_min_css = "~/Content/elfinder/css/elfinder.min.css";
                        public const string theme_css = "~/Content/elfinder/css/theme.css";
                    }
                }
                public static partial class img 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class js 
                {
                    public static partial class i18n 
                    {
                        public static class Assets
                        {
                            public const string elfinder_ar_js = "~/Content/elfinder/js/i18n/elfinder.ar.js"; 
                            public const string elfinder_bg_js = "~/Content/elfinder/js/i18n/elfinder.bg.js"; 
                            public const string elfinder_ca_js = "~/Content/elfinder/js/i18n/elfinder.ca.js"; 
                            public const string elfinder_cs_js = "~/Content/elfinder/js/i18n/elfinder.cs.js"; 
                            public const string elfinder_de_js = "~/Content/elfinder/js/i18n/elfinder.de.js"; 
                            public const string elfinder_el_js = "~/Content/elfinder/js/i18n/elfinder.el.js"; 
                            public const string elfinder_es_js = "~/Content/elfinder/js/i18n/elfinder.es.js"; 
                            public const string elfinder_fa_js = "~/Content/elfinder/js/i18n/elfinder.fa.js"; 
                            public const string elfinder_fr_js = "~/Content/elfinder/js/i18n/elfinder.fr.js"; 
                            public const string elfinder_hu_js = "~/Content/elfinder/js/i18n/elfinder.hu.js"; 
                            public const string elfinder_it_js = "~/Content/elfinder/js/i18n/elfinder.it.js"; 
                            public const string elfinder_jp_js = "~/Content/elfinder/js/i18n/elfinder.jp.js"; 
                            public const string elfinder_ko_js = "~/Content/elfinder/js/i18n/elfinder.ko.js"; 
                            public const string elfinder_LANG_js = "~/Content/elfinder/js/i18n/elfinder.LANG.js"; 
                            public const string elfinder_nl_js = "~/Content/elfinder/js/i18n/elfinder.nl.js"; 
                            public const string elfinder_no_js = "~/Content/elfinder/js/i18n/elfinder.no.js"; 
                            public const string elfinder_pl_js = "~/Content/elfinder/js/i18n/elfinder.pl.js"; 
                            public const string elfinder_pt_BR_js = "~/Content/elfinder/js/i18n/elfinder.pt_BR.js"; 
                            public const string elfinder_ru_js = "~/Content/elfinder/js/i18n/elfinder.ru.js"; 
                            public const string elfinder_tr_js = "~/Content/elfinder/js/i18n/elfinder.tr.js"; 
                            public const string elfinder_vi_js = "~/Content/elfinder/js/i18n/elfinder.vi.js"; 
                            public const string elfinder_zh_CN_js = "~/Content/elfinder/js/i18n/elfinder.zh_CN.js"; 
                        }
                    }
                    public static class Assets
                    {
                        public const string elfinder_full_js = "~/Content/elfinder/js/elfinder.full.js"; 
                        public const string elfinder_min_js = "~/Content/elfinder/js/elfinder.min.js"; 
                    }
                }
                public static partial class sounds 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class themes 
            {
                public static partial class ui_lightness 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                        public const string jquery_ui_css = "~/Content/themes/ui-lightness/jquery-ui.css";
                        public const string jquery_ui_accordion_css = "~/Content/themes/ui-lightness/jquery.ui.accordion.css";
                        public const string jquery_ui_all_css = "~/Content/themes/ui-lightness/jquery.ui.all.css";
                        public const string jquery_ui_autocomplete_css = "~/Content/themes/ui-lightness/jquery.ui.autocomplete.css";
                        public const string jquery_ui_base_css = "~/Content/themes/ui-lightness/jquery.ui.base.css";
                        public const string jquery_ui_button_css = "~/Content/themes/ui-lightness/jquery.ui.button.css";
                        public const string jquery_ui_core_css = "~/Content/themes/ui-lightness/jquery.ui.core.css";
                        public const string jquery_ui_datepicker_css = "~/Content/themes/ui-lightness/jquery.ui.datepicker.css";
                        public const string jquery_ui_dialog_css = "~/Content/themes/ui-lightness/jquery.ui.dialog.css";
                        public const string jquery_ui_progressbar_css = "~/Content/themes/ui-lightness/jquery.ui.progressbar.css";
                        public const string jquery_ui_resizable_css = "~/Content/themes/ui-lightness/jquery.ui.resizable.css";
                        public const string jquery_ui_selectable_css = "~/Content/themes/ui-lightness/jquery.ui.selectable.css";
                        public const string jquery_ui_slider_css = "~/Content/themes/ui-lightness/jquery.ui.slider.css";
                        public const string jquery_ui_tabs_css = "~/Content/themes/ui-lightness/jquery.ui.tabs.css";
                        public const string jquery_ui_theme_css = "~/Content/themes/ui-lightness/jquery.ui.theme.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string Site_css = "~/Content/Site.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


